### ISSUE TITLE
chromedriver location not saved

### ISSUE THREAD

**Issue by sullo** [phefley/burp-javascript-security-extension#2]
The chromedriver location is not saved in the project settings. It must be re-selected every time.

BurpSuite v2.0.23beta
OS X 10.14.5

**Comment by sullo** [comment]
Branch: Master

**Comment by phefley** [comment]
Fix implemented in branch iss2_driver_location_setting, jar v1.1.2. Will merge pending testing. Thanks for reporting the issue! :-)

**Comment by phefley** [comment]
Merged in to master. Will send a pull request to the bapp store folks. Thanks!
